resource_names = [
    'UNDO_bits_32x48.png',
    'addpoint_bits_32x48.png',
    'beforeframe_bits_24x48.png',
    'beframe_bits_24x48.png',
    'color_bits_32x48.png',
    'copy_bits_32x30.png',
    'delface_bits_32x48.png',
    'delpoint_bits_32x48.png',
    'facecopy_bits_32x48.png',
    'facecut_bits_32x48.png',
    'faceflip_bits_32x48.png',
    'facemove_bits_32x48.png',
    'facerotate_bits_32x48.png',
    'facescale_bits_32x48.png',
    'faceselect_bits_32x48.png',
    'faceside_bits_32x48.png',
    'flip_bits_32x48.png',
    'goframe_bits_32x48.png',
    'kminus_bits_32x20.png',
    'kplus_bits_32x20.png',
    'make_bits_32x48.png',
    'minus_bits_32x30.png',
    'mirror_bits_32x48.png',
    'nexframe_bits_24x48.png',
    'nextframe_bits_24x48.png',
    'plus_bits_32x30.png',
    'point_bits_32x48.png',
    'pointmove_bits_32x48.png',
    'pointrotate_bits_32x48.png',
    'pointscale_bits_32x48.png',
    'pointselect_bits_32x48.png',
    'primitive_bits_32x48.png',
    'scale_down_bits_32x15.png',
    'scale_up_bits_32x15.png',
    'state_bits_32x48.png',
    'toguru_bits_48x24.png',
    'topfram_bits_24x48.png',
    'transfer_bits_32x48.png',
]

foreach resource_name : resource_names
    configure_file(input: resource_name, output: resource_name, copy: true)
endforeach
