#pragma once

#include <stdint.h>

/* Stable editor command identities.  Menu layout is deliberately kept out of
   the dispatch contract so separators and reordered rows cannot change what a
   click executes. */
typedef enum CadCommandId {
    CAD_COMMAND_NONE = 0,
    CAD_COMMAND_FILE_NEW,
    CAD_COMMAND_FILE_OPEN,
    CAD_COMMAND_FILE_SAVE,
    CAD_COMMAND_FILE_SAVE_AS,
    CAD_COMMAND_FILE_IMPORT_3DG1,
    CAD_COMMAND_FILE_IMPORT_OBJ,
    CAD_COMMAND_FILE_EXPORT_3DG1,
    CAD_COMMAND_FILE_EXPORT_OBJ,
    CAD_COMMAND_FILE_LOAD_COLOR,
    CAD_COMMAND_FILE_LOAD_PALETTE,
    CAD_COMMAND_FILE_ANIMATION,
    CAD_COMMAND_FILE_OPEN_SHAPE_FOLDER,
    CAD_COMMAND_FILE_QUIT,
    CAD_COMMAND_EDIT_UNDO,
    CAD_COMMAND_EDIT_REDO,
    CAD_COMMAND_EDIT_PASTE,
    CAD_COMMAND_EDIT_COPY,
    CAD_COMMAND_WINDOW_TOP,
    CAD_COMMAND_WINDOW_FRONT,
    CAD_COMMAND_WINDOW_RIGHT,
    CAD_COMMAND_WINDOW_3D,
    CAD_COMMAND_WINDOW_COORDINATES,
    CAD_COMMAND_WINDOW_TOOL_PALETTE,
    CAD_COMMAND_WINDOW_TEN_KEY,
    CAD_COMMAND_WINDOW_CLEAN_UP,
    CAD_COMMAND_WINDOW_HOME,
    CAD_COMMAND_WINDOW_RESET_SCALES,
    CAD_COMMAND_OPTION_AREA_SELECT,
    CAD_COMMAND_OPTION_SELECT_ALL,
    CAD_COMMAND_OPTION_CHANGE_FIRST_POINT,
    CAD_COMMAND_OPTION_FLAT_CHECK,
    CAD_COMMAND_OPTION_FACE_SUPPORT,
    CAD_COMMAND_OPTION_FACE_INFORMATION,
    CAD_COMMAND_OPTION_WIREFRAME,
    CAD_COMMAND_OPTION_SOLID,
    CAD_COMMAND_MERGE_STATUS,
    CAD_COMMAND_MERGE_GRID,
    CAD_COMMAND_MERGE_POINTS,
    CAD_COMMAND_MERGE_POLYGONS,
    CAD_COMMAND_MERGE_ALL,
    CAD_COMMAND_POLYGON_SORT
} CadCommandId;

enum {
    CAD_MENU_ITEM_SEPARATOR = 1u << 0,
    CAD_MENU_ITEM_SUBMENU = 1u << 1,
    CAD_MENU_ITEM_DISABLED = 1u << 2
};

typedef struct CadMenuItemDescriptor {
    CadCommandId command;
    const char* label;
    uint16_t flags;
} CadMenuItemDescriptor;
